### ISSUE TITLE
Flip images

### ISSUE THREAD

**Issue by SteegHobland** [MikkCZ/rotate-and-zoom-image#13]
Please add a feature to flip images horizontally or vertically.

**Comment by MikkCZ** [comment]
Hi @SteegHobland, thank you for your suggestion. Adding flip to the set of supported transformations won't be hard, but at this moment I am working on other projects, so it can take me few weeks to get to this.

If there is someone who wants to try this, I will be happy to mentor. Just a basic knowledge of JS and CSS is needed.

**Comment by SteegHobland** [comment]
You're adding the flip feature, that's great! Thanks. :)
