### ISSUE TITLE
Add "Fit to window" option

### ISSUE THREAD

**Issue by tomaszg7** [MikkCZ/rotate-and-zoom-image#16]
I think it is more or less self-explanatory :)

**Comment by MikkCZ** [comment]
From https://addons.mozilla.org/firefox/addon/rotate-and-zoom-image/reviews/960060/
> hold right click then left click to give you max visibility zoom, to resize the image to fit your page

**Comment by MikkCZ** [comment]
Can it just open the image in a separate tab, or would you prefer it changes the size in-page, in the content?
