### ISSUE TITLE
Add mouse support

### ISSUE THREAD

**Issue by tomaszg7** [MikkCZ/rotate-and-zoom-image#17]
It would be quite nice if it could be controlled via mouse buttons/wheel - especially if the bindings would be configurable.

**Comment by unknownsoldierx** [comment]
Yes! I used to use Image Zoom for this, but it is not compatible with FF57.

Image Zoom had the great feature where you could hold the right mouse button on an image and use the scroll wheel to zoom it in and out.

**Comment by MikkCZ** [comment]
From https://addons.mozilla.org/cs/firefox/addon/rotate-and-zoom-image/reviews/960060/
> hold right click on the image then scrollbar up/down to adjust zoom level, including out and in

**Comment by strahlc** [comment]
yes, please implement 😄

**Comment by jedikalimero** [comment]
> 
> 
> From https://addons.mozilla.org/firefox/addon/rotate-and-zoom-image/reviews/960060/
> 
> > The features were:
> > hold right click on the image then scrollbar up/down to adjust zoom level, including out and in.
> > hold right click then left click to give you max visibility zoom, to resize the image to fit your page.
> > hold right click then scrollbar click to reset to normal

I suppose by "scrollbar" they mean "Mouse Wheel". I used to use Image Zoom and I greatly miss these shortcuts. It would be awesome if you could implement them to your add on.

I would also add something like, lets say left click + scrollbar up or down to rotate right or left respectively.

All shortcuts should be customizable to avoid conflict with other add ons that may be using the same combination for something.
