### ISSUE TITLE
No Flip Option :(

### ISSUE THREAD

**Issue by Sofia1234567890** [MikkCZ/rotate-and-zoom-image#19]
Hi, as now the bad quantum forced intall is hitting, they messed up with everything, so most add-on work no more I was using "Image rotate or flip" now I got your but seen with stupefaction and disdain that you have no flip option (horizontal and vertical) which is a must have, I removed the addon, I would reinstall if this is implemented in a very near future.

**Comment by MikkCZ** [comment]
Thank you Sofia for your request. This has been already requested in #13 and will be in the next version, which is soon to come.
