### ISSUE TITLE
HTML5 Canvas issues

### ISSUE THREAD

**Issue by kenyoni** [MikkCZ/rotate-and-zoom-image#20]
Does not recognize images in an HTML5 canvas. An example of this is the "RRT-Connect algorithm" image at the bottom of [this](http://www.lingzhuxiang.com/) page. The image menu (rt click) does not contain the rotate-and-zoom-image option. Select 'View Image', and the resulting image is recognized by rotate-and-zoom-image, but any attempts to zoom or rotate are unsuccessful.

For reference, the "Image Zoom" FF extension handle[sd] this correctly, including allowing the demo to run resized.

**Comment by MikkCZ** [comment]
I am afraid the extensions API does not offer an option to create context menu for canvas out of the box. But I will try to add it in the next version.

**Comment by MikkCZ** [comment]
Unfortunately [there is no way to implement context menu for canvas](https://discourse.mozilla.org/t/context-menu-for-canvas/22740) at the moment. The only would be to show the context menu for each an every element, which might be a confusing. But if there is no API, it may be worth trying to actually allow to rotate and zoom not just images, but anything.

**Comment by kenyoni** [comment]
I think that just might be a kinda cool feature to have if it works out. 

rotate-and-zoom-anything. :)
