### ISSUE TITLE
Allow to move context menu items to the top most level possible

### ISSUE THREAD

**Issue by DataPacRat** [MikkCZ/rotate-and-zoom-image#21]
Moving a mouse pointer to the narrow field to expand a menu, without accidentally moving it off the field, can be slow. I suggest that some of the core items be moved to where they can be selected with "right click, select option, click", rather than "right click, hover mouse over field, slide mouse to right without hovering over another field, click". The items I recommend the most for this are 'fit to screen', 'fit to browser width', 'double current zoom', and/or 'halve current zoom'.

**Comment by MikkCZ** [comment]
Together with #6, I could probably make the context menu items configurable too.

But AFAIK the WebExtensions API does not allow multiple top level menu items, so you will always have to go at least one step deep.
