### ISSUE TITLE
Doesn't work for images on a wall in vk.com

### ISSUE THREAD

**Issue by EnverOsmanov** [MikkCZ/rotate-and-zoom-image#26]
### Steps to reproduce

1.  Open https://vk.com/wall91523534_3881
2. Try to rotate image

### Expected behavior

Image rotated

### Actual behavior

Image wasn't rotated

**Comment by MikkCZ** [comment]
Hi @EnverOsmanov .

Thank you for reporting this. Unfortunately the images in VKontakte are not standard `<img>` HTML tags, but a link element with `background-image` styling property (#4). Supporting such elements properly would be really hard and it will need to offer rotating for elements, which are not actually images. That may really decrease the usability and confuse users.

I understand it would be nice if the extensions can do it, but I don't see a solution without usability regressions now. Sorry... :(
