### ISSUE TITLE
Missfunction of zooming

### ISSUE THREAD

**Issue by mdziczkowski** [MikkCZ/rotate-and-zoom-image#27]
I want to report that while zooming in, the image is beeeing cut-off in some parts (aspecially from the top and/or bottom) and it's restored while using the "reset" function. Please fix it asap because it makes hard to enjoy the pics while they are cropped and unable to scroll

**Comment by MikkCZ** [comment]
Hi Michal.

Can you please send me a link of a specific page + which specific picture on that page, where I could reproduce it? If possible, accessible without registration or login.

Thank you

**Comment by mdziczkowski** [comment]
This happens on most of images I try to zoom in, independant from the page on with I try to do it  
            
          
     
      
       
        Dnia 29 października 2019 11:00 Michal Stanke &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Hi Michal. 
 Can you please send me a link of a specific page + which specific picture on that page, where I could reproduce it? If possible, accessible without registration or login. 
 Thank you

**Comment by mdziczkowski** [comment]
it&#39;s strange that the images are cropped just one sided fpr the time of zoom in and the cropping is undone when clicking the &#34;reset&#34; position from the context sub-menu.   Maybe you could try find out why it&#39;s cropped only on one side (usually top or bottom) and use the same rule from the unaffected side for the cropping one.   Michal  
            
          
     
      
       
        Dnia 30 października 2019 14:40 Michal Stanke &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Hi Michał. 
 The only way I was able to reproduce is when the images have some parent that is limiting the ability of the images to overflow. An example are preview images on the cnn.com homepage for example. 
 Unfortunately I don&#39;t know a straightforward way to tackle this, if the add-on should. Actually the only thing this extension does is to apply some basic CSS rules for the image and the rest of the page is not adjusted for it in any way. 
 If you have an idea to solve this issue, I will be happy to implement it. As I am not using the extension, I haven&#39;t updated it for almost 2 years, so there are definitely ways to do things better.
